CREATE TABLE IF NOT EXISTS dim_ins_guarantee_company_info_full_t(
	company_name STRING COMMENT '企业名称',
	 social_credit_code STRING COMMENT '统一社会信用代码',
	 company_tag STRING COMMENT 'RPA原始业务标签，分号分隔',
	 national_standard_industry STRING COMMENT '国标完整行业路径',
	 main_industry STRING COMMENT '所属一级行业，取自国标行业第一级',
	 sub_industry STRING COMMENT '细分行业：优先取最后一级中文，无中文取次一级，剔除末尾行业编码',
	 industry_code STRING COMMENT '国民经济GB/T4754行业编码，取自末尾括号内编码',
	 scale STRING COMMENT '企业规模：大型/中型/小型/微型',
	 address STRING COMMENT '注册地址，保函申请方优先，兜底RPA完整地址',
	 company_location STRING COMMENT '企业所在省份，直辖市取市',
	 capital_attribute STRING COMMENT '资本属性：优先标签，无标签取enterprise_type括号内原文',
	 enterprise_type STRING COMMENT '工商企业类型',
	 registered_capital DECIMAL(20,2) COMMENT '注册资本',
	 legal_person STRING COMMENT '法定代表人',
	 legal_id_card STRING COMMENT '法人身份证号',
	 bank_account_name STRING COMMENT '对公账户名称',
	 bank_account_no STRING COMMENT '对公银行账号',
	 bank_name STRING COMMENT '开户银行',
	 risk_tags STRING COMMENT '企业风险标签，多个逗号分隔：司法案件,合作风险',
	 honor_tags STRING COMMENT '企业荣誉资质标签，多个逗号分隔：企业技术中心,新四板(正常上市)',
	 dw_create_time TIMESTAMP COMMENT '数据写入时间',
	 dw_update_time TIMESTAMP COMMENT '数据更新时间') STORED AS aliorc 
TBLPROPERTIES ('columnar.nested.type'='true',
	 'comment'='保函业务企业维表，合并保函申请方数据+RPA采集工商信息（普通表）');