##正堂
SELECT  recon_date, product_no, apply_no, term, repay_date, act_repay_date, compensate_date, compensate_type, status, ovd_days, is_compensate, print, int_amt, service_amt, guarantee_amt, margin_amt, compensate_amt, oint_amt, oguarantee_amt, define_amt, adv_define_amt, repay_total_amt, act_print, act_int_amt, act_service_amt, act_guarantee_amt, act_margin_amt, act_compensate_amt, act_oint_amt, act_oguarantee_amt, act_define_amt, act_adv_define_amt, act_repay_total_amt, compensate_print, compensate_int_amt, compensate_oint_amt, is_reduce, reduce_amt, coupon_amt, remark, loan_month, act_reduce_print, act_reduce_int_amt, act_reduce_service_amt, act_reduce_guarantee_amt, act_reduce_margin_amt, act_reduce_compensate_amt, act_reduce_oint_amt, act_reduce_oguarantee_amt, act_reduce_define_amt, act_reduce_adv_define_amt
FROM ln_plan_info WHERE id>370217658;

select recon_date, product_no, apply_no, term, tran_rp_no, repay_time, repay_total_amt, print, int_amt, service_amt, guarantee_amt, margin_amt, compensate_amt, oint_amt, oguarantee_amt, define_amt, adv_define_amt, reduce_print, reduce_int_amt, reduce_service_amt, reduce_guarantee_amt, reduce_margin_amt, reduce_compensate_amt, reduce_oint_amt, reduce_oguarantee_amt, reduce_define_amt, reduce_adv_define_amt, repay_type, reduce_activity_amt, reduce_compliance_amt, remark
from ln_repay_info where recon_date >='2025-02-01' and recon_date<='2024-12-31';

select * from ln_loan_info_copy1 where id >'750241';


select recon_date, product_no, apply_no, term, tran_rp_no, repay_time, repay_total_amt, print, int_amt, service_amt, guarantee_amt, margin_amt, compensate_amt, oint_amt, oguarantee_amt, define_amt, adv_define_amt, reduce_print, reduce_int_amt, reduce_service_amt, reduce_guarantee_amt, reduce_margin_amt, reduce_compensate_amt, reduce_oint_amt, reduce_oguarantee_amt, reduce_define_amt, reduce_adv_define_amt, repay_type, reduce_activity_amt, reduce_compliance_amt, remark
from  ln_repay_info where update_time >= '2025-01-06';


select  recon_date, product_no, apply_no, term, tran_rp_no, repay_time, repay_total_amt, print, int_amt, service_amt, guarantee_amt, margin_amt, compensate_amt, oint_amt, oguarantee_amt, define_amt, adv_define_amt, reduce_print, reduce_int_amt, reduce_service_amt, reduce_guarantee_amt, reduce_margin_amt, reduce_compensate_amt, reduce_oint_amt, reduce_oguarantee_amt, reduce_define_amt, reduce_adv_define_amt, repay_type, reduce_activity_amt, reduce_compliance_amt, remark from ln_repay_info where id >'227880910' order by apply_no;

select recon_date, product_no, apply_no, term, repay_date, act_repay_date, compensate_date, compensate_type, status, ovd_days, is_compensate, print, int_amt, service_amt, guarantee_amt, margin_amt, compensate_amt, oint_amt, oguarantee_amt, define_amt, adv_define_amt, repay_total_amt, act_print, act_int_amt, act_service_amt, act_guarantee_amt, act_margin_amt, act_compensate_amt, act_oint_amt, act_oguarantee_amt, act_define_amt, act_adv_define_amt, act_repay_total_amt, compensate_print, compensate_int_amt, compensate_oint_amt, is_reduce, reduce_amt, coupon_amt, remark, loan_month, act_reduce_print, act_reduce_int_amt, act_reduce_service_amt, act_reduce_guarantee_amt, act_reduce_margin_amt, act_reduce_compensate_amt, act_reduce_oint_amt, act_reduce_oguarantee_amt, act_reduce_define_amt, act_reduce_adv_define_amt from ln_plan_info order by apply_no;

select recon_date, apply_no, name, id_card, id_card_type, id_address, id_expiry_date, mobile, gender, educational, address_time, address, detail_address, house_condition, car_condition, annual_income, is_pay_security, debts, often_email, marry_status, has_children, salary_date, industry, unit_name, unit_address, unit_detail_address, unit_telphone, contact_a_ref, contact_a_name, contact_a_mobile, contact_b_ref, contact_b_name, contact_b_mobile, work_years, apply_ref, is_common_apply, ent_name, ent_id, ent_create_date, legal_name, industry_code, industry_divide, ent_type, area_name, registration_authority, person_number, registered_address, business_scope, contact_c_name, contact_c_ref, contact_c_mobile, last_year_begin_total_assets, last_year_begin_total_liabilities, last_year_end_total_assets, last_year_end_total_liabilities, last_year_annual_income, is_tree_year_tax_penalty, litigation_amt, is_enforcement, is_dishonesty, is_high_consumption, is_business_abnormal, is_stock_equity_freeze, is_administrative_penalty, account_name, card_no, pre_mobile, partner_no, loan_use, loan_amt, loan_period, face_merchants, facce_supply_param, face_card_compare, product_no, product_name, apply_time, loan_title, apply_status, guarantee_type, buis_mode, rev_guarantee_type, guarantee_scope, cfund_channel_no, cfund_channel_name, pay_way, repay_way, year_rate, service_rate, guarantee_rate, margin_rate, compensate_rate, act_year_rate, period_service_rate, period_guarantee_rate, period_margin_rate, period_compensate_rate, oint_rate, oguarantee_rate, define_rate, adv_define_rate, compensate_days, grace_day, interest_free_period, credit_time, credit_no, credit_apply_no from apply_base_info order by apply_no;

select recon_date, product_no, apply_no, loan_req_no, loan_time, due_date, name, id_card_type, id_card, contract_amt, loan_amt, service_amt, guarantee_amt, margin_amt, compensate_amt, act_service_amt, act_guarantee_amt, act_margin_amt, act_compensate_amt, repay_day, total_term, loan_status, remark, loan_month, lend_status from ln_loan_info order by apply_no;

#昌泰度小满
select  recon_date, product_no, apply_no, term, tran_rp_no, repay_time, repay_total_amt, print, int_amt, service_amt, guarantee_amt, margin_amt, compensate_amt, oint_amt, oguarantee_amt, define_amt, adv_define_amt, reduce_print, reduce_int_amt, reduce_service_amt, reduce_guarantee_amt, reduce_margin_amt, reduce_compensate_amt, reduce_oint_amt, reduce_oguarantee_amt, reduce_define_amt, reduce_adv_define_amt, repay_type, reduce_activity_amt, reduce_compliance_amt, remark
from ln_repay_info where id >523071;

select recon_date, product_no, apply_no, term, repay_date, act_repay_date, compensate_date, compensate_type, status, ovd_days, is_compensate, print, int_amt, service_amt, guarantee_amt, margin_amt, compensate_amt, oint_amt, oguarantee_amt, define_amt, adv_define_amt, repay_total_amt, act_print, act_int_amt, act_service_amt, act_guarantee_amt, act_margin_amt, act_compensate_amt, act_oint_amt, act_oguarantee_amt, act_define_amt, act_adv_define_amt, act_repay_total_amt, compensate_print, compensate_int_amt, compensate_oint_amt, is_reduce, reduce_amt, coupon_amt, remark, loan_month, act_reduce_print, act_reduce_int_amt, act_reduce_service_amt, act_reduce_guarantee_amt, act_reduce_margin_amt, act_reduce_compensate_amt, act_reduce_oint_amt, act_reduce_oguarantee_amt, act_reduce_define_amt, act_reduce_adv_define_amt
from ln_plan_info where id> 927192;

select recon_date, apply_no, name, id_card, id_card_type, id_address, id_expiry_date, mobile, gender, educational, address_time, address, detail_address, house_condition, car_condition, annual_income, is_pay_security, debts, often_email, marry_status, has_children, salary_date, industry, unit_name, unit_address, unit_detail_address, unit_telphone, contact_a_ref, contact_a_name, contact_a_mobile, contact_b_ref, contact_b_name, contact_b_mobile, work_years, apply_ref, is_common_apply, ent_name, ent_id, ent_create_date, legal_name, industry_code, industry_divide, ent_type, area_name, registration_authority, person_number, registered_address, business_scope, contact_c_name, contact_c_ref, contact_c_mobile, last_year_begin_total_assets, last_year_begin_total_liabilities, last_year_end_total_assets, last_year_end_total_liabilities, last_year_annual_income, is_tree_year_tax_penalty, litigation_amt, is_enforcement, is_dishonesty, is_high_consumption, is_business_abnormal, is_stock_equity_freeze, is_administrative_penalty, account_name, card_no, pre_mobile, partner_no, loan_use, loan_amt, loan_period, face_merchants, facce_supply_param, face_card_compare, product_no, product_name, apply_time, loan_title, apply_status, guarantee_type, buis_mode, rev_guarantee_type, guarantee_scope, cfund_channel_no, cfund_channel_name, pay_way, repay_way, year_rate, service_rate, guarantee_rate, margin_rate, compensate_rate, act_year_rate, period_service_rate, period_guarantee_rate, period_margin_rate, period_compensate_rate, oint_rate, oguarantee_rate, define_rate, adv_define_rate, compensate_days, grace_day, interest_free_period, credit_time, credit_no, credit_apply_no
from apply_base_info where id>=81000 and id<84500;

select recon_date, product_no, apply_no, loan_req_no, loan_time, due_date, name, id_card_type, id_card, contract_amt, loan_amt, service_amt, guarantee_amt, margin_amt, compensate_amt, act_service_amt, act_guarantee_amt, act_margin_amt, act_compensate_amt, repay_day, total_term, loan_status, remark, loan_month, lend_status
from ln_loan_info  where id>=81000 and id<84500;


