CREATE TABLE IF NOT EXISTS dim_req_supervision_payment_info_full_t(
	business_control_rule_id BIGINT NOT NULL COMMENT '业务管控规则Id',
	 project_no BIGINT COMMENT '项目编号',
	 project_name STRING COMMENT '项目名称',
	 bill_app_no STRING NOT NULL COMMENT '借款申请编号',
	 product_no STRING COMMENT '产品编码',
	 product_name STRING COMMENT '产品名称',
	 financer_no STRING COMMENT '资金编号',
	 financer_name STRING COMMENT '资金方名称',
	 platform_no STRING COMMENT '平台编号',
	 platform_name STRING COMMENT '平台名称',
	 guarantor_no STRING COMMENT '担保方编号',
	 guarantor_name STRING COMMENT '担保方名称',
	 name STRING COMMENT '客户姓名',
	 loan_day DATE COMMENT '贷款日期，格式yyyy-MM-dd',
	 loan_year BIGINT COMMENT '贷款年份',
	 total_term BIGINT COMMENT '总期次',
	 loan_amt DECIMAL(38,18) COMMENT '贷款金额',
	 id_card STRING COMMENT '身份证号',
	 mobile STRING COMMENT '手机号',
	 province_id STRING COMMENT '省份编号',
	 gender STRING COMMENT '性别',
	 age BIGINT COMMENT '年龄',
	 loan_period BIGINT COMMENT '贷款期限',
	 city_id STRING COMMENT '用户所在市',
	 farmer_flag STRING COMMENT '农户标识：0-非农户 1-农户 -99 ：身份证具体地址缺失',
	 loan_req_no STRING COMMENT '放款流水号',
	 enterp_sc STRING COMMENT '中小微划型',
	 indiv_cust_id STRING COMMENT '客户号',
	 id_card_type STRING COMMENT '证件类型',
	 address STRING COMMENT '所在地区',
	 is_cancel STRING COMMENT '是否撤保',
	 rev_guarantee_type STRING COMMENT '反担保方式',
	 act_year_rate DECIMAL(38,18) COMMENT '实际年化利率',
	 loan_use STRING COMMENT '借款用途',
	 grace_day BIGINT COMMENT '宽限期',
	 is_local_guarantee_business STRING COMMENT '是否本地担保',
	 customer_type STRING COMMENT '客户类型',
	 repayment_method STRING COMMENT '还款方式',
	 loan_balance DECIMAL(38,18) COMMENT '资金在贷余额',
	PRIMARY KEY(bill_app_no,
	 business_control_rule_id)) STORED AS aliorc 
TBLPROPERTIES ('cdc.data.retain.hours'='0',
	 'acid.cdc.mode.enable'='false',
	 'acid.data.retain.hours'='0',
	 'columnar.nested.type'='true',
	 'comment'='展示系统放款借据信息（简版借据）',
	 'transactional'='true',
	 'write.bucket.num'='64');
