CREATE TABLE IF NOT EXISTS ads_hain_g11_cust_info(
	dbank_id STRING COMMENT '机构代码',
	 ddate STRING COMMENT '报表日期',
	 xh BIGINT COMMENT '序号',
	 cust_id STRING COMMENT '客户编号',
	 cust_name STRING COMMENT '客户名称',
	 biz_body STRING COMMENT '经营主体',
	 cust_type STRING COMMENT '客户类型',
	 hold_type STRING COMMENT '控股类型',
	 cert_type STRING COMMENT '证件类型',
	 cert_no STRING COMMENT '证件号码',
	 region STRING COMMENT '所在地区',
	 industry STRING COMMENT '所属行业',
	 ent_scale STRING COMMENT '企业规模',
	 emp_num BIGINT COMMENT '从业人员',
	 annual_inc DECIMAL(20,2) COMMENT '年营业收入',
	 asset_tot DECIMAL(20,2) COMMENT '资产总额',
	 credit_rate STRING COMMENT '主体信用评级',
	 agri_flag STRING COMMENT '"三农"主体标志',
	 farmer_flag STRING COMMENT '农户标志',
	 new_agri_flag STRING COMMENT '新型农业主体标志',
	 dual_innov_flag STRING COMMENT '双创双服主体标志',
	 grp_uscc STRING COMMENT '所属集团统一社会信用代码',
	 create_time STRING COMMENT '创建时间',
	 update_time STRING COMMENT '修改时间') STORED AS aliorc 
TBLPROPERTIES ('columnar.nested.type'='true',
	 'comment'='融资担保公司客户信息表');