/******************************************/
/*   DatabaseName = prd_spark_db   */
/*   TableName = ods_cons_td_repay_info   */
/******************************************/
CREATE TABLE `ods_cons_td_repay_info` (
  `id` bigint AUTO_INCREMENT COMMENT '物理主键',
  `recon_date` date NOT NULL COMMENT '对账日期：格式YYYY-MM-DD',
  `loan_no` varchar(64) NOT NULL COMMENT '借款申请编号',
  `term` int NOT NULL COMMENT '期次号',
  `repay_time` datetime COMMENT '还款时间',
  `tran_rp_no` varchar(64) NOT NULL COMMENT '还款流水号',
  `print` decimal(17, 2) NOT NULL DEFAULT '0.00' COMMENT '还款本金',
  `int_amt` decimal(17, 2) NOT NULL DEFAULT '0.00' COMMENT '还款利息',
  `oint_amt` decimal(17, 2) NOT NULL DEFAULT '0.00' COMMENT '还款罚息',
  `guarantee_amt` decimal(17, 2) NOT NULL DEFAULT '0.00' COMMENT '还款担保费',
  `adv_define_amt` decimal(17, 2) NOT NULL DEFAULT '0.00' COMMENT '提前还款违约金',
  `reduce_amt` decimal(17, 2) NOT NULL DEFAULT '0.00' COMMENT '减免金额',
  `reduce_int_amt` decimal(17, 2) NOT NULL DEFAULT '0.00' COMMENT '减免利息',
  `reduce_oint_amt` decimal(17, 2) NOT NULL DEFAULT '0.00' COMMENT '减免罚息',
  `reduce_adv_define_amt` decimal(17, 2) NOT NULL DEFAULT '0.00' COMMENT '减免提前还款违约金',
  `repay_type` varchar(4) DEFAULT '1' COMMENT '还款类型 1-正常还款 2-提前结清 3-单笔代偿 4-整笔代偿 5-追偿',
  `remark` varchar(100) COMMENT '备注',
  `create_time` timestamp COMMENT '创建时间',
  `submitted` varchar(2) COMMENT '报送标识',
  `dw_update_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数仓更新时间',
  `dw_create_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '数仓创建时间',
  `service_amt` decimal(17, 2) NOT NULL DEFAULT '0.00' COMMENT '实还服务费',
  `margin_amt` decimal(17, 2) NOT NULL DEFAULT '0.00' COMMENT '实还保证金',
  `compensate_amt` decimal(17, 2) NOT NULL DEFAULT '0.00' COMMENT '实还代偿金',
  `define_amt` decimal(17, 2) NOT NULL DEFAULT '0.00' COMMENT '实还违约金',
  `product_no` varchar(64) COMMENT '产品编码',
  `update_time` timestamp COMMENT '更新时间',
  KEY `idx_repay_recon_date` (`recon_date`),
  KEY `idx_repay_time` (`repay_time`),
  KEY `idx_submitted` (`submitted`),
  KEY `pk_sys_id` (`id`),
  PRIMARY KEY (`id`)
) DISTRIBUTE BY HASH(`id`) STORAGE_POLICY='HOT' ENGINE='XUANWU_V2' TABLE_PROPERTIES='{"format":"columnstore"}' COMMENT='通道还款明细'
;



/******************************************/
/*   DatabaseName = prd_spark_db   */
/*   TableName = ods_cons_td_loan   */
/******************************************/
CREATE TABLE `ods_cons_td_loan` (
  `recon_date` date NOT NULL,
  `product_no` varchar(64) NOT NULL COMMENT '产品编号',
  `bill_app_no` varchar(64) NOT NULL COMMENT '借据号',
  `loan_amt` decimal(17, 2) DEFAULT '0.00' COMMENT '借款金额',
  `name` varchar(64) COMMENT '借款人姓名',
  `id_card` varchar(64) COMMENT '身份证号',
  `mobile` varchar(32) COMMENT '联系电话',
  `sex` varchar(8) COMMENT '性别',
  `age` tinyint COMMENT '年龄',
  `purpose` varchar(8) COMMENT '贷款用途',
  `year_rate` decimal(17, 6) DEFAULT '0.000000' COMMENT '年利率',
  `loan_day` date COMMENT '放款日',
  `end_date` date COMMENT '到期日',
  `loan_term` tinyint DEFAULT '0' COMMENT '期数',
  `loan_bal` decimal(17, 2) DEFAULT '0.00',
  `ovd_days` int DEFAULT '0',
  `status` varchar(8) COMMENT '借据状态：NOR-正常,OD-逾期中,FP-结清',
  `repay_type` varchar(8) COMMENT '客户还款方式01按期还款02提前结清03代偿',
  `repay_prin_amt` decimal(17, 2) DEFAULT '0.00' COMMENT '数据日还款金额(本金)',
  `compensate_amt` decimal(17, 2) DEFAULT '0.00' COMMENT '截止数据日代偿金额(本金)',
  `bill_repay_type` varchar(8) COMMENT '借据还款方式00等额本金02先息后本10随借随还',
  `create_time` timestamp,
  `update_time` timestamp,
  `dw_create_time` timestamp DEFAULT CURRENT_TIMESTAMP,
  `company_size` varchar(32) COMMENT '企业规模，企业用户必填，个人用户为空',
  `enterprise_type` varchar(8) COMMENT '资本属性：1-国有控股，2-民营控股，3-外资控股，企业用户必填，个人用户为空',
  `agriculture_related` varchar(8) COMMENT '是否涉农：1-是, 0-否, "-99"-无地址',
  `act_year_rate` decimal(17, 6) COMMENT '资方利率(年利率)，年化利率IRR（资方口径，综合利率IRR）',
  `compensate_type` varchar(8) COMMENT '代偿类型：1-当期代偿，2-整笔代偿（当还款类型为03时，必填）',
  `act_compensate_amt` decimal(17, 2) COMMENT '代偿总额，累计代偿金额',
  `act_compensate_int_amt` decimal(17, 2) COMMENT '代偿罚息，累计代偿罚息',
  `act_compensate_define_amt` decimal(17, 2) COMMENT '代偿违约金，累计代偿违约金',
  `recovery_type` varchar(8) COMMENT '追偿类型：1-普通追偿，2-挽回损失（还款类型为05时必填）',
  `id_card_type` varchar(10) COMMENT '证件类型',
  `id_address` varchar(256) COMMENT '身份证地址',
  `education` varchar(20) COMMENT '学历',
  `marray_status` varchar(10) COMMENT '婚姻状态',
  `mate_name` varchar(64) COMMENT '配偶姓名',
  `mate_id_type` varchar(10) COMMENT '配偶证件类型',
  `mate_id` varchar(64) COMMENT '配偶身份证号',
  `mate_telephone` varchar(32) COMMENT '配偶手机号',
  `mate_unit_name` varchar(128) COMMENT '配偶工作单位',
  `mate_unit_address` varchar(256) COMMENT '配偶工作地址',
  `degree` varchar(20) COMMENT '学位',
  `emp_status` varchar(20) COMMENT '就业状况',
  `unit_name` varchar(128) COMMENT '单位名称',
  `unit_type` varchar(20) COMMENT '单位性质',
  `industry` varchar(20) COMMENT '单位所属行业',
  `unit_address` varchar(256) COMMENT '单位地址',
  `unit_mail_code` varchar(10) COMMENT '单位邮编',
  `unit_address_code` varchar(20) COMMENT '单位地行政区划代码',
  `unit_telephone` varchar(32) COMMENT '单位电话',
  `occupation_duty` varchar(20) COMMENT '职业',
  `post` varchar(20) COMMENT '职务',
  `occupation_title` varchar(20) COMMENT '职称',
  `work_years` varchar(10) COMMENT '单位工作年限',
  `living_condition` varchar(20) COMMENT '居住状况',
  `living_address` varchar(256) COMMENT '居住地详细地址',
  `living_mail_code` varchar(10) COMMENT '居住地邮编',
  `living_address_code` varchar(20) COMMENT '居住地行政区划代码',
  `living_telephone` varchar(32) COMMENT '住宅电话',
  `com_address` varchar(256) COMMENT '通讯地址',
  `com_mail_code` varchar(10) COMMENT '通讯地邮编',
  `com_address_code` varchar(20) COMMENT '通讯地行政区划代码',
  `customer_id` varchar(64) COMMENT '客户唯一编码',
  `domicile_code` varchar(20) COMMENT '身份证地址行政区划代码',
  `property_address` varchar(256) COMMENT '抵押房产地址',
  `owner_name` varchar(100) COMMENT '抵押房产产权人',
  `int_amt` decimal(17, 2) COMMENT '应还利息',
  `service_amt` decimal(17, 2) COMMENT '应还服务费',
  `guarantee_amt` decimal(17, 2) COMMENT '应还担保费',
  `margin_amt` decimal(17, 2) COMMENT '应还保证金',
  `oint_amt` decimal(17, 2) COMMENT '应还罚息',
  `define_amt` decimal(17, 2) COMMENT '应还逾期违约金',
  `adv_define_amt` decimal(17, 2) COMMENT '应还提前还款违约金',
  `total_act_int` decimal(17, 2) COMMENT '累计还款利息',
  `total_act_service` decimal(17, 2) COMMENT '累计还服务费',
  `total_act_guarantee` decimal(17, 2) COMMENT '累计还担保费',
  `total_act_margin` decimal(17, 2) COMMENT '累计还保证金',
  `total_act_compensate` decimal(17, 2) COMMENT '累计还代偿金',
  `total_act_oint` decimal(17, 2) COMMENT '累计还罚息',
  `total_act_define` decimal(17, 2) COMMENT '累计还违约金',
  `total_act_adv_define` decimal(17, 2) COMMENT '累计还提前还款违约金',
  `act_compensate_int` decimal(17, 2) COMMENT '代偿利息',
  `guarantee_type` varchar(10) COMMENT '担保账户类型',
  `guarantee_category` varchar(20) COMMENT '担保业务大类',
  `guarantee_category_detail` varchar(20) COMMENT '担保业务种类细分',
  `counter_guarantee_type` varchar(20) COMMENT '反担保方式',
  `other_repayment` varchar(50) COMMENT '其他还款保证方式',
  `security_deposit` decimal(10, 4) COMMENT '保证金比例',
  `contract_code` varchar(64) COMMENT '担保合同编号',
  `initial_creditor` varchar(100) COMMENT '初始债权人',
  `initial_creditor_code` varchar(64) COMMENT '初始债权人机构代码',
  `original_debt_type` varchar(10) COMMENT '原债务类型',
  `owed_compensate_amt` decimal(17, 2) COMMENT '应还代偿金',
  `dw_update_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数仓更新时间',
  `guarantee_status` varchar(1) COMMENT '担保账户状态：1-正常(代表担保关系依然生效) 2-关闭(代表担保关系已经解除)',
  `act_compensate_princ` decimal(17, 2) COMMENT '实际代偿本金',
  `property_nature` varchar(50) COMMENT '房产性质：1-住宅 2-非住宅',
  PRIMARY KEY (`bill_app_no`)
) DISTRIBUTE BY HASH(`bill_app_no`) INDEX_ALL='Y' STORAGE_POLICY='HOT' ENGINE='XUANWU' TABLE_PROPERTIES='{"format":"columnstore"}' COMMENT='消金通道借据信息'
;


/******************************************/
/*   DatabaseName = test_zxbs_db   */
/*   TableName = dim_mortgage_info_d   */
/******************************************/
CREATE TABLE `dim_mortgage_info_d` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `mortgagor` varchar(500) COMMENT '抵押人',
  `property_address` varchar(1000) COMMENT '物业地址',
  `sign_order` varchar(20) COMMENT '签单',
  `amount` decimal(18, 2) COMMENT '金额',
  `loan_term` varchar(100) COMMENT '借款期限',
  `record_date` date COMMENT '日期',
  `guarantee_contract_no` varchar(200) COMMENT '担保服务合同编号',
  `is_residential` varchar(50) COMMENT '是否住宅',
  `is_mortgage_success` varchar(50) COMMENT '是否办抵成功',
  `mortgage_date` date COMMENT '办抵日期',
  `release_date` date COMMENT '解抵日期',
  `guarantee_balance` decimal(18, 2) COMMENT '在保余额',
  `guarantee_fee` decimal(18, 2) COMMENT '担保费',
  `create_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  KEY `pk_sys_id` (`id`),
  PRIMARY KEY (`id`)
) DISTRIBUTE BY HASH(`id`) STORAGE_POLICY='HOT' ENGINE='XUANWU_V2' TABLE_PROPERTIES='{"format":"columnstore"}' COMMENT='办抵解抵信息维度表'
;
